### ISSUE TITLE
Error:Authentication scheme 'all'(Authentication) is not supported by protocol 'file'

### ISSUE THREAD

**Issue by arniesaha** [atooma/demo-android-resonance-ai#1]
Hello Folks,

When trying to build the demo resonance apk. This entry in the gradle causing the mentioned build error.

maven {
            url "url.xx.xx"
            credentials {
                username "519xxx"
                password "4HXxxx"
            }
        }

Error:Authentication scheme 'all'(Authentication) is not supported by protocol 'file'

I'm on Android Studio 2.2.3
Java: 1.8.0_121
Android SDK: 25

Thanks,
Arnab

**Comment by ninniuz** [comment]
Hello @arniesaha,
thanks for getting in touch and for your bug report.
Would you mind trying again adding `https://` in front of the URL you got in the developer console?
This should fix the error you are getting when building the demo project using Gradle.

If this is not the case it would be of great help if you could provide a stacktrace of the error with
```
./gradlew clean assembleDebug --stacktrace
```

Please do not hesitate to contact us if you have any further questions or doubts.

Cheers
Andrea

**Comment by arniesaha** [comment]
Hi Andrea,

Thanks for the reply. Had the chance to come back to try this out, while the app itself builds as expected. Faced some issues in dashboard in terms of UI experience (not letting me create a new project or edit existing project to edit the android package name) Anyway, I did manage to delete the old project and created a new one with the sample apps package name.

Configured accordingly, and the app launches. But doesn't register below stacktrace:

`03-23 12:40:14.108 17954-17954/? I/art: Late-enabling -Xcheck:jni
03-23 12:40:14.149 17954-17961/? I/art: Debugger is no longer active
03-23 12:40:14.149 17954-17961/? I/art: Starting a blocking GC Instrumentation
03-23 12:40:14.178 17954-17954/? D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
03-23 12:40:14.183 17954-17954/? D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
03-23 12:40:14.191 17954-17954/? I/FA: App measurement is starting up, version: 10084
03-23 12:40:14.192 17954-17954/? I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
03-23 12:40:14.192 17954-17954/? D/FA: Debug-level message logging enabled
03-23 12:40:14.192 17954-17954/? D/FA: AppMeasurement singleton hash: 94102814
03-23 12:40:14.201 17954-17954/? V/FA: Collection enabled
03-23 12:40:14.201 17954-17954/? V/FA: App package, google app id: com.resonance_ai.sdk.sampleapp, 1:379928096870:android:c6a67115a92d37c4
03-23 12:40:14.202 17954-17954/? I/FA: To enable faster debug mode event logging run:
                                         adb shell setprop debug.firebase.analytics.app com.resonance_ai.sdk.sampleapp
03-23 12:40:14.219 17954-17954/? V/FA: Registered activity lifecycle callback
03-23 12:40:14.220 17954-17954/? I/FirebaseInitProvider: FirebaseApp initialization successful
03-23 12:40:14.231 17954-17981/? V/FA: Using measurement service
03-23 12:40:14.232 17954-17981/? V/FA: Connecting to remote service
03-23 12:40:14.245 17954-17954/? W/art: Before Android 4.1, method double java.util.concurrent.ThreadLocalRandom.internalNextDouble(double, double) would have incorrectly overridden the package-private method in java.util.Random
03-23 12:40:14.245 17954-17954/? W/art: Before Android 4.1, method int java.util.concurrent.ThreadLocalRandom.internalNextInt(int, int) would have incorrectly overridden the package-private method in java.util.Random
03-23 12:40:14.245 17954-17954/? W/art: Before Android 4.1, method long java.util.concurrent.ThreadLocalRandom.internalNextLong(long, long) would have incorrectly overridden the package-private method in java.util.Random
03-23 12:40:14.265 17954-17954/? D/NetworkSecurityConfig: No Network Security Config specified, using platform default
03-23 12:40:14.406 17954-17954/? D/ActorSystem: Wakelock acquired
03-23 12:40:14.410 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@ba42f
03-23 12:40:14.411 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@6c4c11a
03-23 12:40:14.411 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@ba42f
03-23 12:40:14.411 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d2cee28
03-23 12:40:14.412 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@7ddd4e6
03-23 12:40:14.412 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@382967d
03-23 12:40:14.412 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@80d01c3
03-23 12:40:14.412 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@7a71d79
03-23 12:40:14.415 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@6c4c11a
03-23 12:40:14.415 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d2cee28
03-23 12:40:14.415 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@7ddd4e6
03-23 12:40:14.415 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@382967d
03-23 12:40:14.416 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@80d01c3
03-23 12:40:14.416 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@7a71d79
03-23 12:40:14.417 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@daae63b
03-23 12:40:14.417 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@daae63b
03-23 12:40:14.419 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@657ab17
03-23 12:40:14.420 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@657ab17
03-23 12:40:14.420 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d4b18ed
03-23 12:40:14.421 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d4b18ed
03-23 12:40:14.421 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@f23d370
03-23 12:40:14.421 17954-17992/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@f23d370
03-23 12:40:14.421 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@84ee60f
03-23 12:40:14.421 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@84ee60f
03-23 12:40:14.422 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d12d47a
03-23 12:40:14.422 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d12d47a
03-23 12:40:14.423 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@8effa21
03-23 12:40:14.423 17954-17982/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@5a38807
03-23 12:40:14.424 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@8effa21
03-23 12:40:14.425 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@5a38807
03-23 12:40:14.428 17954-17954/? W/InstanceID/Rpc: Found 10036
03-23 12:40:14.457 17954-17954/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter android.support.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
03-23 12:40:14.461 17954-17954/? V/FA: onActivityCreated
03-23 12:40:14.487 17954-17983/? I/TextToSpeech: Sucessfully bound to com.google.android.tts
03-23 12:40:14.488 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@b845b64
03-23 12:40:14.488 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@b845b64
03-23 12:40:14.488 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@fddc9d0
03-23 12:40:14.489 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@fddc9d0
03-23 12:40:14.489 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@99897ef
03-23 12:40:14.490 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@99897ef
03-23 12:40:14.490 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@f2e17da
03-23 12:40:14.491 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@41102e8
03-23 12:40:14.491 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@165d7a6
03-23 12:40:14.491 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@f2e17da
03-23 12:40:14.491 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d676594
03-23 12:40:14.491 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@41102e8
03-23 12:40:14.491 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@165d7a6
03-23 12:40:14.491 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d676594
03-23 12:40:14.501 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@f1a4871
03-23 12:40:14.502 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@f1a4871
03-23 12:40:14.502 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@f95bc4
03-23 12:40:14.502 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@f95bc4
03-23 12:40:14.508 17954-17990/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@b48fa2e
03-23 12:40:14.509 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@b48fa2e
03-23 12:40:14.509 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@1ccd265
03-23 12:40:14.510 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@55923eb
03-23 12:40:14.510 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@1ccd265
03-23 12:40:14.510 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@55923eb
03-23 12:40:14.510 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@5bd2fe1
03-23 12:40:14.510 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@5bd2fe1
03-23 12:40:14.510 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@5cd3df4
03-23 12:40:14.510 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@5cd3df4
03-23 12:40:14.510 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@ac42563
03-23 12:40:14.511 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@ac42563
03-23 12:40:14.512 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@b72fa19
03-23 12:40:14.512 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d2e578c
03-23 12:40:14.512 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@b72fa19
03-23 12:40:14.513 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d2e578c
03-23 12:40:14.513 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@b2036ea
03-23 12:40:14.513 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@b2036ea
03-23 12:40:14.513 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d60d351
03-23 12:40:14.513 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d60d351
03-23 12:40:14.514 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@48e538d
03-23 12:40:14.515 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@48e538d
03-23 12:40:14.515 17954-17990/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d9c690
03-23 12:40:14.516 17954-17990/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@31f4baf
03-23 12:40:14.516 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d9c690
03-23 12:40:14.516 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@31f4baf
03-23 12:40:14.516 17954-17990/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@1f76745
03-23 12:40:14.516 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@1f76745
03-23 12:40:14.518 17954-17990/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@a1ef3cb
03-23 12:40:14.518 17954-17990/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@a1ef3cb
03-23 12:40:14.525 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@40e9a66
03-23 12:40:14.527 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@40e9a66
03-23 12:40:14.531 17954-17991/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@cb81143
03-23 12:40:14.531 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@cb81143
03-23 12:40:14.531 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@f8c903e
03-23 12:40:14.532 17954-17993/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@f8c903e
03-23 12:40:14.532 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d99abb5
03-23 12:40:14.532 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d99abb5
03-23 12:40:14.532 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@6247ad8
03-23 12:40:14.532 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@6247ad8
03-23 12:40:14.532 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@47da297
03-23 12:40:14.533 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@47da297
03-23 12:40:14.533 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@7efd133
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@34bccf0
03-23 12:40:14.533 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@74c4d8f
03-23 12:40:14.533 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@7efd133
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@6b8c81c
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@b4dec25
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@7bf01fa
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@c984a08
03-23 12:40:14.533 17954-17982/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@74c4d8f
03-23 12:40:14.533 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@d9625a1
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@3eb43c6
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@af65f87
03-23 12:40:14.533 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@56bfeb4
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@94f6d23
03-23 12:40:14.534 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@a47d652
03-23 12:40:14.534 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@d9625a1
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@6245220
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@33ce7d9
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@a69059e
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@18b2895
03-23 12:40:14.534 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@6dbddaa
03-23 12:40:14.534 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@a47d652
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@4a35d9b
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@f64538
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@342b911
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@c503877
03-23 12:40:14.534 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@6dbddaa
03-23 12:40:14.534 17954-17993/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@2667ce4
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@c08d54d
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@74e7802
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@885e513
03-23 12:40:14.534 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@2667ce4
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@a9a7949
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@c30124e
03-23 12:40:14.534 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@c5fbf6f
03-23 12:40:14.535 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@ff2847c
03-23 12:40:14.535 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@2886105
03-23 12:40:14.535 17954-17983/? D/Engine: com.resonance_ai.actor.e.d$a@7f055a
03-23 12:40:14.535 17954-17983/? D/Engine: com.resonance_ai.engine.internals.a$b@752e38b
03-23 12:40:14.539 17954-17981/? V/FA: Using measurement service
03-23 12:40:14.539 17954-17981/? V/FA: Connection attempt already in progress
03-23 12:40:14.539 17954-17954/? I/com.resonance_ai.sdk.sampleapp.MainActivity@8e69da3: //com.resonance_ai.sdk.sampleapp.MainActivity@8e69da3: Subscribing
03-23 12:40:14.539 17954-17981/? V/FA: Activity resumed, time: 146570451
03-23 12:40:14.540 17954-17983/? D/EventBusActor: Publishing: com.resonance_ai.actor.b.a$g@8216c68
03-23 12:40:14.540 17954-17991/? D/Server: onReceive: com.resonance_ai.actor.b.a$g@8216c68
03-23 12:40:14.541 17954-17954/? D/ResonanceActivity: starting recognition...
03-23 12:40:14.544 17954-17992/? D/EventBusActor: Publishing: com.resonance_ai.engine.internals.a.f@c3c9575
03-23 12:40:14.560 17954-17954/? E/GcmTaskService: Unknown action received null, terminating
03-23 12:40:14.561 17954-17954/? D/EngineService: STARTING ENGINE
03-23 12:40:14.565 17954-17954/? I/TextToSpeech: Connected to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
03-23 12:40:14.565 17954-18004/? I/RegIntentService: FCM Registration Token: fEvZV7qdOEk:APA91bE6gZE3ja7QJRYJ5OBgiQBBSZGgtcPDRZyh-u3_4U7Q6HAlctpyzmKYb-lD52JTRiao7H9y4tgSApGi730Ly8qI6kPqng1DSlREN-369Dv3pJjM9uzrMAiEYV-BsgyeTFP7zqvH
03-23 12:40:14.571 17954-18006/? I/TextToSpeech: Set up connection to ComponentInfo{com.google.android.tts/com.google.android.tts.service.GoogleTTSService}
03-23 12:40:14.584 17954-17983/? D/Server: onReceive: RegisterEvent{uids=[110, 147, 53, 113, 91, 149, 108, 26, 82, 111, 54, 146, 112, 90, 52, 58, 131, 55, 51, 83, 157, 153, 84, 121, 67, 65, 19, 78, 3, 4, 135, 61, 59, 70, 133, 86, 106, 107, 66]events=[SMSSendEvent, SuggestionNewEvent, LocationGeofenceTriggerEvent, SoundSetModeEvent, TwitterRequestAuthEvent, RuleEventsEvent, AlarmClockSetEvent, GoogleRequestAuthEvent, NewLuaRuleEvent, TTSStartEvent, LocationRemoveGeofenceEvent, SyncRemoteUpdatesEvent, ContactGetEvent, TwitterAuthURLEvent, LocationAddGeofenceEvent, StorageGetEvent, GetPlacesEvent, NotificationShowEvent, LocationGetCurrentEvent, RemoveLuaRuleEvent, NestRequestAuthEvent, NetatmoRequestAuthEvent, StorageClearEvent, PermissionAskEvent, WifiGetStatusEvent, WifiDisableEvent, BatteryGetStatusEvent, FitbitRequestAuthEvent, DisabledRuleEvent, EnabledRuleEvent, UserWorkEvent, TimezoneGetEvent, StoragePutEvent, NotificatonShowToastEvent, UserHomeEvent, FacebookRequestAuthEvent, AppStartEvent, AlarmClockGetEvent, WifiEnableEvent]}
03-23 12:40:14.600 17954-18002/? I/Adreno: QUALCOMM build                   : b6da14b, I47548ba842
                                           Build Date                       : 11/22/16
                                           OpenGL ES Shader Compiler Version: XE031.09.00.03
                                           Local Branch                     : 
                                           Remote Branch                    : quic/LA.BR.1.3.6_rb1.9
                                           Remote Branch                    : NONE
                                           Reconstruct Branch               : NOTHING
03-23 12:40:14.603 17954-17983/? D/Server: Registering to server.
03-23 12:40:14.609 17954-18002/? I/OpenGLRenderer: Initialized EGL, version 1.4
03-23 12:40:14.609 17954-18002/? D/OpenGLRenderer: Swap behavior 1
03-23 12:40:14.841 17954-17981/? D/FA: Connected to remote service
03-23 12:40:14.842 17954-17981/? V/FA: Processing queued up service tasks: 2
03-23 12:40:14.923 17954-17983/? D/EventBusActor: Publishing: com.resonance_ai.engine.modules.location.a.a@ece09c1
03-23 12:40:14.969 17954-17992/? D/EventBusActor: Publishing: LocationDataEvent{deviceId='null', userspaceId='null', apiKey='null', ddid='null', intermediate='null', fromServer=false}
03-23 12:40:14.997 17954-17992/? D/EventBusActor: Publishing: RawSampleEvent{deviceId='null', userspaceId='null', apiKey='null', ddid='null', intermediate='null', fromServer=false}
03-23 12:40:15.024 17954-18028/? E/ActivityDetection: not enough samples to process
03-23 12:40:19.866 17954-17981/com.resonance_ai.sdk.sampleapp V/FA: Inactivity, disconnecting from the service
03-23 12:40:24.253 17954-17984/com.resonance_ai.sdk.sampleapp D/ActorSystem: Wakelock released
03-23 12:40:24.638 17954-17954/com.resonance_ai.sdk.sampleapp D/ActorSystem: Wakelock acquired
03-23 12:40:24.639 17954-17991/com.resonance_ai.sdk.sampleapp D/EventBusActor: Publishing: com.resonance_ai.engine.adapters.b$b@d8df2bd
03-23 12:40:24.639 17954-17991/com.resonance_ai.sdk.sampleapp D/EventBusActor: Publishing: GoogleCheckAuthEvent{deviceId='null', userspaceId='null', apiKey='null', ddid='null', intermediate='null', fromServer=false}
03-23 12:40:24.878 17954-17984/com.resonance_ai.sdk.sampleapp D/ActorSystem: Wakelock released
03-23 12:40:25.077 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err: java.net.SocketTimeoutException: timeout
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
03-23 12:40:25.078 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.RealCall.getResponse(RealCall.java:241)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
03-23 12:40:25.079 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.RealCall.access$100(RealCall.java:30)
03-23 12:40:25.080 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
03-23 12:40:25.080 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
03-23 12:40:25.080 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
03-23 12:40:25.080 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
03-23 12:40:25.080 17954-18010/com.resonance_ai.sdk.sampleapp W/System.err:     at java.lang.Thread.run(Thread.java:761)
03-23 12:40:25.082 17954-18010/com.resonance_ai.sdk.sampleapp D/ActorSystem: Wakelock acquired
03-23 12:40:25.084 17954-17991/com.resonance_ai.sdk.sampleapp D/EventBusActor: Publishing: com.resonance_ai.engine.internals.a.c@f9e66d6
03-23 12:40:25.085 17954-17954/com.resonance_ai.sdk.sampleapp I/com.resonance_ai.sdk.sampleapp.MainActivity@8e69da3: //com.resonance_ai.sdk.sampleapp.MainActivity@8e69da3: Received: com.resonance_ai.engine.internals.a.c@f9e66d6
03-23 12:40:25.085 17954-17954/com.resonance_ai.sdk.sampleapp E/ERROR: timeout
03-23 12:40:35.204 17954-17984/com.resonance_ai.sdk.sampleapp D/ActorSystem: Wakelock released
`

Any thoughts,

Arnab
